### ISSUE TITLE
UI freeze because DependencyChecker.getLatestVersion() performs long operations under read action

### ISSUE THREAD

**Issue by alexander-doroshko** [pszklarska/FlutterPubVersionChecker#11]
Hi from JetBrains,
We're getting user reports about IDE freezes caused by the `Flutter Pub Version Checker` plugin (version 1.1.1). It performs long network operation under [read action](http://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/general_threading_rules.html#readwrite-lock). It means that as soon as EDT wants to acquire write action, UI freezes until read action ends. Typical stack trace:
```
"JobScheduler FJ pool 5/11" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.base@11.0.4/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.4/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.4/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.4/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.4/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base@11.0.4/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base@11.0.4/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base@11.0.4/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at java.base@11.0.4/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.4/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.4/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.4/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base@11.0.4/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base@11.0.4/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base@11.0.4/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base@11.0.4/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at pl.pszklarska.pubversionchecker.DependencyChecker.getLatestVersion(DependencyChecker.kt:28)
	at pl.pszklarska.pubversionchecker.FileParser.mapToVersionDescription(FileParser.kt:42)
	at pl.pszklarska.pubversionchecker.FileParser.getVersionsFromFile(FileParser.kt:26)
	at pl.pszklarska.pubversionchecker.FileParser.checkFile(FileParser.kt:16)
	at pl.pszklarska.pubversionchecker.YamlElementVisitor.visitFile(PubPackagesInspection.kt:45)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3708/0x00000001023c8c40.run(Unknown Source)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter$$Lambda$1818/0x0000000101253840.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3707/0x00000001023c8840.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3473/0x0000000102067440.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3474/0x0000000102066840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3472/0x0000000102067040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base@11.0.4/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base@11.0.4/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.4/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base@11.0.4/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base@11.0.4/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base@11.0.4/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by marcglasberg** [comment]
This comes from:
https://youtrack.jetbrains.com/issue/WEB-42685

**Comment by athornz** [comment]
FYI this PR fixes the issue (or greatly reduces the time it takes to check dependencies): https://github.com/pszklarska/FlutterPubVersionChecker/pull/8

**Comment by pszklarska** [comment]
Hi @alexander-doroshko! Thanks for the feedback, PR #8 is already merged, I'll push new update soon. I'll keep an eye on performance issues, in the meantime I'm closing this issue.
