### ISSUE TITLE
Plugin throws when encounters git repo dependency

### ISSUE THREAD

**Issue by jaggernod** [pszklarska/FlutterPubVersionChecker#17]
The plugin does not report any values when it tries to resolve git repository dependency.

```
  background:
    git:
      url: git@github.com:upday/background_flutter.git
      ref: v1.0.0
```

Exception: 
```
2020-04-11 11:49:30,170 [  26386]  ERROR - aemon.impl.PassExecutorService - pl.pszklarska.pubversionchecker.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: ref: v1.0.0 
java.lang.RuntimeException: pl.pszklarska.pubversionchecker.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: ref: v1.0.0
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:88)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:333)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:203)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1109)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: pl.pszklarska.pubversionchecker.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: ref: v1.0.0
	at pl.pszklarska.pubversionchecker.DependencyChecker.getLatestVersion(DependencyChecker.kt:37)
	at pl.pszklarska.pubversionchecker.FileParser.mapToVersionDescription(FileParser.kt:55)
	at pl.pszklarska.pubversionchecker.FileParser.access$mapToVersionDescription(FileParser.kt:11)
	at pl.pszklarska.pubversionchecker.FileParser$getVersionsFromFile$$inlined$map$lambda$1.invokeSuspend(FileParser.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

```

**Comment by pszklarska** [comment]
Hi @jaggernod! Thanks for your feedback, there's already similar issue reported here: https://github.com/pszklarska/FlutterPubVersionChecker/issues/14, so I'm closing this one. I have a plan to make this improvement in the next release, so stay tuned!
