### ISSUE TITLE
Plugin 1.2.5 : IDE Fatal Errors

### ISSUE THREAD

**Issue by ghost** [pszklarska/FlutterPubVersionChecker#33]
Firstly, thank you for your plugin, it work well <3
But i got an error :

```bash
kotlin.KotlinNullPointerException
	at pl.pszklarska.pubversionchecker.DependencyChecker.getLatestVersion(DependencyChecker.kt:28)
	at pl.pszklarska.pubversionchecker.FileParser.mapToVersionDescription(FileParser.kt:56)
	at pl.pszklarska.pubversionchecker.FileParser.access$mapToVersionDescription(FileParser.kt:12)
	at pl.pszklarska.pubversionchecker.FileParser$getVersionsFromFile$$inlined$map$lambda$1.invokeSuspend(FileParser.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n_extension: 4.1.3

  cupertino_icons: 1.0.3

  # Firebase mobile stats & notification
  firebase_core: 1.7.0
  firebase_analytics: 8.3.3
  firebase_crashlytics: 2.2.3
  firebase_messaging: 10.0.8

  shared_preferences: 2.0.8
  flutter_svg: 0.22.0
  auto_size_text: 3.0.0-nullsafety.0
  cached_network_image: 3.1.0
  url_launcher: 6.0.12
  shimmer: 2.0.0
  http: 0.13.4
  flutter_html: 2.1.5
```

```dart
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
```

**Comment by pszklarska** [comment]
Hey @EA-YOUHOU, thank you for reporting that issue! I released an update yesterday that should fix that. The newest version (1.2.6) will be ready to download in the next 1-2 days :) 

I'm closing that issue, if you still have problems after the update, feel free to reopen it.
